export { Logo } from './img/logo.png'
export { Background } from './img/bg.jpeg'
export { Humidity } from './img/humidity.png'
export { Pressure } from './img/pressure.png'
export { Wind } from './img/wind.png'